[package]
name = "lose_where_hoho_you_lose_why_is"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
